### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by mayfinn** [finnge/vis-covid19-flights#8]
Depends on #3 

Show multiple dates with timeline
- [x] Research on COVID-19 events
- [x] Concept in Figma/Sketch

Acceptance Criteria:
- [x] Progress bar
- [ ] Automatic Player
- [ ] Hints with COVID-19 specific events

**Comment by Libao1** [comment]
Research COVID-19 events:
### 2019/2020
- 31.12.19 China meldet Ausbruch einer mysteriösen Lungenkrankheit (KW 1)
- 07.01.20 Identifizierung des Coronavirus (KW 2)
- 24.01.20 Erste Fälle in Europa (KW 4)
- 30.01.20 WHO "internationale gesundheitliche Notlage" (KW 5)
- 11.02.20 WHO Namensgebung "COVID-19" (KW 7)
- 11.03.20 WHO erklärt die bisherige Epidemie offiziell zu einer weltweiten Pandemie (KW 11)
- 16.03.20 Soziale Isolation in DE, Ausgangssperre in FR -> Europa wird zum Corona-Hotspot (KW 12)
- 21.03.20 Italiens Gesundheitssystem ist am Limit (KW 12)
- 07.20      Reiserückkehrer aus Risikogebieten müssen sich testen lassen
- 09.20      zweite Welle in Europa
- 13.10.20 Rat nimmt Empfehlung für einen gemeinsamen Ansatz für Reisebestimmungen an (KW 42)
- 21.12.20 Erster COVID-19-Impfstoff zur Verwendung in der EU zugelassen (KW 52)
- 12.20      Virusvariante Alpha&Beta gemeldet

### 2021
- 01.21      Virusvariante Gamma gemeldet
- 06.01.21 COVID-19-Impfstoff zugelassen (Moderna) (KW 1)
- 23.01.21 COVID-19-Impfstoff zugelassen (AstraZeneca) (KW 3)
- 01.02.21 Rat aktualisiert Empfehlung zu COVID-19-Reisemaßnahmen (KW 5)
- 11.03.21 COVID-19-Impfstoff zugelassen (J&J) (KW 10)
- 11.05.21 Virusvariante Delta gemeldet (KW 19)
- 21.07.21 Digitales COVID-Zertifikat der EU tritt in Kraft (KW 29)
- 24.11.21 Virusvariante Omikron gemeldet (KW 47)

### 2022
- 25.01.22 Europäischer Rat verabschiedet neue Empfehlung zu COVID-19-Reisebestimmungen (KW 4)

--- 

Quellen: 
- https://www.bundesgesundheitsministerium.de/coronavirus/chronik-coronavirus.html
- https://zdfheute-stories-scroll.zdf.de/corona/coronavirus/chronik/ausbruch/
- https://www.consilium.europa.eu/de/policies/coronavirus/timeline/
