### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by mayfinn** [finnge/vis-covid19-flights#9]
Animation of onboarding process

Acceptance criteria:
- [x] Concept for onboarding steps
- [x] Develop multiple animations

**Comment by mayfinn** [comment]
@leo-3108 First step: Konzeption

Beispiel: http://bl.ocks.org/nbremer/94db779237655907b907

**Comment by leo-3108** [comment]
Storyboard fürs Onboarding (Work in Progress):
https://www.figma.com/file/b3PBJW3iHh2Cdxmqb80gF2/Konzeption-Onboarding?node-id=0%3A1
